# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-15 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra large'), ('u', 'Unknown')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(blank=True, choices=[('l', 'Liked'), ('d', 'Disliked')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(blank=True, choices=[('b', 'Baby'), ('y', 'Young'), ('a', 'Adult'), ('s', 'Senior')], max_length=4),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra large')], max_length=4),
        ),
    ]
