# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20191015_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.CharField(max_length=255),
        ),
    ]
