# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_auto_20191025_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', max_length=8),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='f', max_length=4),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='xl', max_length=8),
        ),
    ]
