# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-25 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0005_auto_20191025_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b', max_length=8),
        ),
    ]
