# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-27 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0006_auto_20191025_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='dog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pugorugh.Dog'),
        ),
    ]
