# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-28 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0009_auto_20191028_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra large'), ('u', 'Unknown')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='xl', max_length=9),
        ),
    ]
